// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-qB-Xjw7_6Kra6B8VN5UnNd-T7Wk6cKI',
    appId: '1:281920884335:web:9bf67a3297b4e093a3079a',
    messagingSenderId: '281920884335',
    projectId: 'appussd-c0385',
    authDomain: 'appussd-c0385.firebaseapp.com',
    storageBucket: 'appussd-c0385.firebasestorage.app',
    measurementId: 'G-CH463TXN6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7niDdeOor1SgUJ8_YFl_Ir8b6y1zPjag',
    appId: '1:281920884335:android:ce82e67062800b74a3079a',
    messagingSenderId: '281920884335',
    projectId: 'appussd-c0385',
    storageBucket: 'appussd-c0385.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8D2MoD7orfENO-VHt7nUpg5UZRoa2DF0',
    appId: '1:281920884335:ios:020b1d5023fbef57a3079a',
    messagingSenderId: '281920884335',
    projectId: 'appussd-c0385',
    storageBucket: 'appussd-c0385.firebasestorage.app',
    iosBundleId: 'com.example.gestionMenuUssd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8D2MoD7orfENO-VHt7nUpg5UZRoa2DF0',
    appId: '1:281920884335:ios:020b1d5023fbef57a3079a',
    messagingSenderId: '281920884335',
    projectId: 'appussd-c0385',
    storageBucket: 'appussd-c0385.firebasestorage.app',
    iosBundleId: 'com.example.gestionMenuUssd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-qB-Xjw7_6Kra6B8VN5UnNd-T7Wk6cKI',
    appId: '1:281920884335:web:d3a802642fb8748fa3079a',
    messagingSenderId: '281920884335',
    projectId: 'appussd-c0385',
    authDomain: 'appussd-c0385.firebaseapp.com',
    storageBucket: 'appussd-c0385.firebasestorage.app',
    measurementId: 'G-9B0K0T52KB',
  );
}



